config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :locations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'locations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	#attr_accessible :address, :latitude, :longitude
	#attr_accessor :address, :latitude, :longitude
	belongs_to :user

	mount_uploader :image, ImageUploader

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
    
    validates :body, presence: true
	validates :title, presence: true, length: { minimum: 1 }
	validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	mount_uploader :image, ImageUploader

	validates :body, presence: true
	validates :title, presence: true, length: { minimum: 1 }
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :locations
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all.order('created_at DESC')
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    #@location = Location.new
    @location = current_user.locations.build
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = current_user.locations.build(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:image, :title, :body, :address, :latitude, :longitude)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
  	params.require(:user).permit(:avatar, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
  	params.require(:user).permit(:avatar, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul>
        <li>
            <h1><li><%= link_to "GastroNaut.gr", root_path, class:"navbar-brand" %></li></h1>
        </li>
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav">

          <% if user_signed_in? %>
             <li style="font-family: 'Spectral SC', serif;"><%= current_user.username %></li>
             <li><%= link_to (image_tag current_user.avatar_url(:avatar_thumb)).to_s %><li>
             <li><%= link_to "acount", edit_user_registration_path, class:"navbar-brand" %></li>
             <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"navbar-brand" %></li>
          <% else %>
             <li><a><%= link_to "Log in", new_user_session_path, class:"navbar-brand" %></a></li>
          <% end %>
          
      </ul>
        <li><a href="#">Links</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
               <% if current_user.admin %>
                <li><a href="#"><%= link_to 'New Location', new_location_path %></a></li>
                <li><a href="#"><%= link_to 'New Post', new_post_path %></a></li>
                <li><a href="#"><%= link_to "posts", posts_path %></a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              <% end %>
            <% end %>
          </ul>
        </li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GastroLatest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Poiret+One" %><!--font-family: 'Poiret One', cursive;-->
    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Playball" %><!--font-family: 'Playball', cursive;-->
    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Spectral+SC" %><!--font-family: 'Spectral SC', serif;-->


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

    <%= render 'layouts/navigation' %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for@location, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :address %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<!-- Stack the columns on mobile by making one full-width and the other half-width -->
<div class="row">
  <div class="col-xs-12 col-md-8">
    <h1 style="font-family: 'Spectral SC', serif;">Events</h1>

  </div>
  <div class="col-xs-6 col-md-4">

     <h1 style="font-family: 'Spectral SC', serif;">Locations</h1>

    <%= form_tag locations_path, :method => :get do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <p style="font-family: 'Spectral SC', serif;"><%= submit_tag "Search Near", :name => nil %></p>
      </p>
    <% end %>

  </div>
</div>

<!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
<div class="row">
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
</div>

<!-- Columns are always 50% wide, on mobile and desktop -->
<% @locations.each do |location| %>
        <div class="row">
         <div class="col-xs-8 col-sm-6"> 
          <div class="post_wrapper">
            
              <a><%= link_to (image_tag location.image_url(:thumb)).to_s %></a>

              <h2 class="title"><%= link_to location.title, location %></h2>
              <!--location.title -->
              <p class="body"><%= truncate(location.body, length:500) %></p>
              <!--location.body -->
              <p class="date"><%= time_ago_in_words(location.created_at) %></p>
              
            </div>
            <br>
          </div>

          <div class="col-xs-4 col-sm-6">
            <div class="post_wrapper">
               <%= image_tag("http://maps.google.com/maps/api/staticmap?size=550x350&sensor=false&zoom=16&markers=#{location.latitude}%2C#{location.longitude}")  %>

              <p class="address"><%= location.address %></p>
              <!--location.address -->
              <p class="location"><%= location.latitude %></p>
              <!--location.latitude-->
              <p class="location"><%= location.longitude %></p>
              <!--location.longitude-->
           </div>
          </div>
        </div>
        <% end %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div class="row">
  <div class="col-sm-9">

    <div class="post_wrapper">
        ....
    </div>
    <br>
    <div class="row">

      <div class="col-xs-8 col-sm-6">
        <div class="post_wrapper">

            <!--image_tag @location.image_url(:thumb).to_s -->
            <!--image_tag @location.image_url.to_s -->
            <%= link_to (image_tag @location.image_url(:thumb)) %>
            
            <h1 style="font-family: 'Poiret One', cursive; color: black;">

               <%= @location.title %>  
            </h1>
            <p style="font-family: 'Poiret One', cursive; color: black;; color: black; font-size: 25px;">
              <%= @location.body %>
            </p>

          <p><%= link_to 'Edit', edit_location_path(@location) %></p>
          <p><%= link_to 'Delete', location_path(@location), method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>

        
        
      </div>

      <div class="col-xs-4 col-sm-6">

        <div class="post_wrapper">

            <%= image_tag("http://maps.google.com/maps/api/staticmap?size=550x400&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" ) %>
              
          
              <ul style="font-family: 'Poiret One', cursive; color: green;">
               <li><%= @location.address %></li>
               <li><%= @location.latitude %></li>
               <li><%= @location.longitude %></li>
              </ul>



        </div>
      </div>

    </div>
    <br>
    <div class="post_wrapper">
     
       <h1 style="font-family: 'Poiret One', cursive; color: black;">
         Nearbys Locations
       </h1>

        <ul>
        <% for location in @location.nearbys(20) %>
        <ul>
           <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
        </ul>
        <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="post_wrapper">
      
      
        <a><%= link_to (image_tag post.image_url(:thumb)).to_s %></a>

        <h2 class="title"><%= link_to post.title, post %></h2>
              <!--location.title -->
        <p class="body"><%= truncate(post.body, length:500) %></p>
              <!--location.body -->
        <p class="date"><%= time_ago_in_words(post.created_at) %></p>
        <br>
        <%= link_to 'Show', post %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <br>
      
    

    </div>
  </div>
</div>
<br>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-9">

    <div class="post_wrapper">

        <h1 style="font-family: 'Poiret One', cursive; color: black;">

          <%= @post.title %>  
        </h1>
    </div>
    <br>
    <div class="row">

      <div class="col-xs-8 col-sm-6">
        <div class="post_wrapper">

            <!--image_tag @location.image_url(:thumb).to_s -->
            <!--image_tag @location.image_url.to_s -->
            <%= link_to (image_tag @post.image_url(:thumb)) %>

            
        </div>

        
        
      </div>

      <div class="col-xs-4 col-sm-6">

        <div class="post_wrapper">
           <p style="font-family: 'Playball', cursive; color: black; font-size: 25px;">
              <%= @post.body %>
            </p>
          
          <p><%= link_to 'Back', posts_path %></p>
          <p><%= link_to 'Edit', edit_post_path(@post) %></p>
          <p><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %></p>




        </div>
      </div>

    </div>
    <br>

  </div>
</div>